update workflows

diff --git a/.github/workflows/check_amalgamate.yml b/.github/workflows/check_amalgamate.yml
--- a/.github/workflows/check_amalgamate.yml
+++ b/.github/workflows/check_amalgamate.yml
@@ -15,5 +15,8 @@ jobs:
 
       - name: Validate Consistency
         run: |
-          git diff --ignore-all-space --ignore-blank-lines --ignore-matching-lines="^// Timestamp: " generator.h || \
-            (echo "::error::generator.h 未与 src/ 同步，请运行 'xmake amalgamate' 并提交更新"; exit 1)
+          git diff --ignore-all-space --ignore-blank-lines --ignore-matching-lines="^// Timestamp: " generator.h
+          if [ $? -ne 0 ]; then
+            echo "::error::generator.h 未与 src/ 同步，请运行 'xmake amalgamate' 并提交更新"
+            exit 1
+          fi
